/// Flutter icons Character
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Character
///      fonts:
///       - asset: fonts/Character.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Character {
  Character._();

  static const _kFontFam = 'Character';

  static const IconData car = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData elephant = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData road = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData eating = IconData(0xe803, fontFamily: _kFontFam);
}
